// <auto-generated />
using System;
using AgentDressReborn.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AgentDress.Migrations
{
    [DbContext(typeof(DressContext))]
    partial class DressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AgentDressReborn.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("DressCategory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("DressId")
                        .HasColumnType("integer");

                    b.Property<string>("Opacity")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("sColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Dress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DressCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("DressTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DressCollectionId");

                    b.HasIndex("DressTypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Dresses");
                });

            modelBuilder.Entity("AgentDressReborn.Model.DressCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DressId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("DressCollections");
                });

            modelBuilder.Entity("AgentDressReborn.Model.DressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DressTypes");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Bik")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Ogrn")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("DressId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("sSize")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int?>("DressId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("PostalCode")
                        .HasColumnType("integer");

                    b.Property<string>("WebSite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Color", b =>
                {
                    b.HasOne("AgentDressReborn.Model.Dress", null)
                        .WithMany("Colors")
                        .HasForeignKey("DressId");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Dress", b =>
                {
                    b.HasOne("AgentDressReborn.Model.Category", "DressCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentDressReborn.Model.DressCollection", null)
                        .WithMany("Dresses")
                        .HasForeignKey("DressCollectionId");

                    b.HasOne("AgentDressReborn.Model.DressType", "DressType")
                        .WithMany()
                        .HasForeignKey("DressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentDressReborn.Model.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentDressReborn.Model.Store", null)
                        .WithMany("Dresses")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("AgentDressReborn.Model.DressCollection", b =>
                {
                    b.HasOne("AgentDressReborn.Model.Dress", null)
                        .WithMany("DressCollections")
                        .HasForeignKey("DressId");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Size", b =>
                {
                    b.HasOne("AgentDressReborn.Model.Dress", null)
                        .WithMany("Sizes")
                        .HasForeignKey("DressId");
                });

            modelBuilder.Entity("AgentDressReborn.Model.Store", b =>
                {
                    b.HasOne("AgentDressReborn.Model.Dress", null)
                        .WithMany("Stores")
                        .HasForeignKey("DressId");
                });
#pragma warning restore 612, 618
        }
    }
}
